- platform: flux
  lights:
    - light.soffa
  name: Flux
  start_time: '6:00'
  stop_time: '21:30'
  start_colortemp: 4000
  sunset_colortemp: 3000
  stop_colortemp: 1900
  disable_brightness_adjust: True
  mode: mired
