- platform: flux
  lights:
    - light.soffa
    - light.matbord
    - light.koksbord
  name: Flux
  start_time: '12:00'
  stop_time: '20:30'
  start_colortemp: 3000
  sunset_colortemp: 2500
  stop_colortemp: 1900
  disable_brightness_adjust: True
  mode: mired
