- platform: flux
  lights:
    - light.matbord
    - light.koksbord
    - light.skarbrada
    - light.hyllor
    - light.klocka
    - light.hall
  name: Flux
  start_time: '9:00'
  stop_time: '23:30'
  start_colortemp: 3500
  sunset_colortemp: 2500
  stop_colortemp: 2000
  disable_brightness_adjust: True
  mode: mired
