- platform: flux
  lights:
    - light.matbord
    - light.koksbord
    - light.skarbrada
    - light.hyllor
    - light.klocka
    - light.hall
    - light.soffa
  name: Flux
  start_time: '9:00'
  stop_time: '23:30'
  start_colortemp: 3500
  sunset_colortemp: 2800
  stop_colortemp: 2400
  disable_brightness_adjust: True
  mode: mired

- platform: flux
  lights:
    - light.tvsoffa
  name: Flux-TV
  start_time: '9:00'
  stop_time: '23:30'
  start_colortemp: 3500
  sunset_colortemp: 2800
  stop_colortemp: 2400
  disable_brightness_adjust: True
  mode: mired

# Temporary workaround until scenes are supported in homekit integration
- platform: template
  switches:
    mysljus:
      value_template: "{{ is_state('scene.mysljus', 'on') }}"
      turn_on:
        service: scene.turn_on
        data:
          entity_id: scene.mysljus
      # Not used, but required for switch
      turn_off:
        service: scene.turn_off
        data:
          entity_id: scene.mysljus

    skymning:
      value_template: "{{ is_state('scene.skymning', 'on') }}"
      turn_on:
        service: scene.turn_on
        data:
          entity_id: scene.skymning
      # Not used, but required for switch
      turn_off:
        service: scene.turn_off
        data:
          entity_id: scene.skymning

    morgon:
      value_template: "{{ is_state('scene.morgon', 'on') }}"
      turn_on:
        service: scene.turn_on
        data:
          entity_id: scene.morgon
      # Not used, but required for switch
      turn_off:
        service: scene.turn_off
        data:
          entity_id: scene.morgon
