- platform: flux
  lights:
    - light.matbord
    - light.koksbord
    - light.skarbrada
    - light.hyllor
    - light.klocka
    - light.hall
  name: Flux
  start_time: '12:00'
  stop_time: '20:30'
  start_colortemp: 3200
  sunset_colortemp: 2500
  stop_colortemp: 1900
  disable_brightness_adjust: True
  mode: mired
