- platform: flux
  lights:
    - light.matbord
    - light.koksbord
    - light.skarbrada
    - light.hyllor
    - light.klocka
    - light.hall
    - light.soffa
  name: Flux
  start_time: '9:00'
  stop_time: '23:30'
  start_colortemp: 3500
  sunset_colortemp: 2800
  stop_colortemp: 2400
  disable_brightness_adjust: True
  mode: mired

- platform: flux
  lights:
    - light.tvsoffa
  name: Flux-TV
  start_time: '9:00'
  stop_time: '23:30'
  start_colortemp: 3500
  sunset_colortemp: 2800
  stop_colortemp: 2400
  disable_brightness_adjust: True
  mode: mired

# Temporary workaround until scenes are supported in homekit integration
- platform: template
  switches:
    mysljus:
      friendly_name: Mysljus
      value_template: "{{ is_state('scene.mysljus', 'on') }}"
      turn_on:
        service: scene.turn_on
        entity_id: scene.mysljus
      turn_off:
        service: switch.turn_off
        entity_id: switch.mysljus

    skymning:
      friendly_name: Skymning
      value_template: "{{ is_state('scene.skymning', 'on') }}"
      turn_on:
        service: scene.turn_on
        entity_id: scene.skymning
      turn_off:
        service: switch.turn_off
        entity_id: switch.skymning

    morgon:
      value_template: "{{ is_state('scene.morgon', 'on') }}"
      friendly_name: Godmorgon
      turn_on:
        service: scene.turn_on
        entity_id: scene.morgon
      turn_off:
        service: switch.turn_off
        entity_id: switch.morgon

    natt:
      value_template: "{{ is_state('scene.natt', 'on') }}"
      friendly_name: Godnatt
      turn_on:
        service: scene.turn_on
        entity_id: scene.natt
      turn_off:
        service: switch.turn_off
        entity_id: switch.natt
