alias: "TV: Apple TV paus (efter solnedgång)"
trigger:
  platform: state
  entity_id: media_player.apple_tv
  from: playing
condition:
  condition: sun
  after: sunset
action:
  service: scene.turn_on
  entity_id: scene.paus
