alias: "TV: Apple TV play"
trigger:
  platform: state
  entity_id: media_player.apple_tv
  to: playing
condition:
  condition: state
  entity_id: input_boolean.evening_lights_turned_on
  state: 'on'
action:
  service: scene.turn_on
  entity_id: scene.play
