alias: "TV: Apple TV paus"
trigger:
  platform: state
  entity_id: media_player.apple_tv
  from: playing
condition:
  condition: state
  entity_id: input_boolean.evening_lights_turned_on
  state: 'on'
action:
  service: scene.turn_on
  entity_id: scene.paus
