# Slå på Apple TV i hass när Sony TV slås på
alias: "TV: Sony TV på (alltid)"
trigger:
  platform: state
  entity_id: media_player.sony_tv
  from: 'off'
  to: 'on'
action:
  - service: remote.turn_on
    entity_id: remote.apple_tv
  - service: light.turn_off
    entity_id:
    - light.matbord
    - light.hall
