alias: "Solnedgång -1h: Tänd lampor om mulet"
trigger:
  platform: sun
  event: sunset
  offset: "-01:00:00"
condition:
  - condition: numeric_state
    entity_id: sensor.yr_cloudiness
    above: 90
  - condition: state
    entity_id: input_boolean.evening_lights_turned_on
    state: 'off'
action:
  service: scene.turn_on
  data_template:
    entity_id: "{% if is_state(\"media_player.sony_tv\", \"on\") %}\n  scene.skymningtv\n\
    {% else %}\n  scene.skymning\n{% endif %}\n"
