alias: "N채rvaro: Sista familjemedlemmen g책r hemifr책n -> Sl채ck alla lampor"
trigger:
  platform: state
  entity_id: group.familj
  from: home
  to: not_home
action:
  data:
    entity_id: group.all_lights
  service: light.turn_off