alias: "Solnedgång: Tänd lampor"
trigger:
  platform: sun
  event: sunset
  offset: "-00:15:00"
condition:
  condition: state
  entity_id: input_boolean.evening_lights_turned_on
  state: 'on'
action:
  service: scene.turn_on
  data_template:
    entity_id: "{% if is_state(\"media_player.sony_tv\", \"on\") %}\n  scene.skymningtv\n\
    {% else %}\n  scene.skymning\n{% endif %}\n"
  service: input_boolean.turn_off
  data:
    entity_id: evening_lights_turned_on
