$(function(){ //DOM Ready

    function navigate(url)
    {
        window.location.href = url;
    }

    $(document).attr("title", "Main Panel");
    content_width = (150 + 5) * 8 + 5
    $('.gridster').width(content_width)
    $(".gridster ul").gridster({
        widget_margins: [5, 5],
        widget_base_dimensions: [150, 150],
        avoid_overlapped_widgets: true,
        max_rows: 15,
        max_size_x: 8,
        shift_widgets_up: false
    }).data('gridster').disable();
    
    // Add Widgets

    var gridster = $(".gridster ul").gridster().data('gridster');
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseclock-default-clock-clock" id="default-clock-clock"><h1 class="date"data-bind="text: date, attr: {style: date_style}"></h1><h2 class="time" data-bind="text: time, attr: {style: time_style}"></h2></div></li>', 2, 1, 1, 1)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-device-tracker-lindasiphone" id="default-device-tracker-lindasiphone"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 1, 2)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-device-tracker-matrix" id="default-device-tracker-matrix"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 2, 2)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-device-tracker-disasiphone" id="default-device-tracker-disasiphone"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 3, 2)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-device-tracker-quack" id="default-device-tracker-quack"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 4, 2)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-group-vardagsrum" id="default-group-vardagsrum"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 1, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-hall" id="default-light-hall"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 2, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-soffa" id="default-light-soffa"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 3, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-matbord" id="default-light-matbord"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 4, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-group-kok" id="default-group-kok"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 1, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-skarbrada" id="default-light-skarbrada"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 2, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-klocka" id="default-light-klocka"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 3, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-hyllor" id="default-light-hyllor"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 4, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-koksbord" id="default-light-koksbord"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 5, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-scene-skymning" id="default-scene-skymning"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 1, 5)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-scene-mysljus" id="default-scene-mysljus"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 2, 5)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-switch-flux" id="default-switch-flux"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 3, 5)
    
    
    
    var widgets = {}
    // Initialize Widgets
    
        widgets["default-clock-clock"] = new baseclock("default-clock-clock", "", "simplyred", {'widget_type': 'baseclock', 'fields': {'date': '', 'time': ''}, 'static_css': {'date_style': 'color: inherit;text-shadow: 3px 3px 8px #BF7F00, -3px -3px 8px #BF7F00;font-weight: 900;font-style: bold;', 'time_style': 'color: inherit;text-shadow: 3px 3px 8px #BF7F00, -3px -3px 8px #BF7F00;font-weight: 900;font-style: bold;', 'widget_style': 'box-shadow: none;background-image: url(/css/simplyred/img/goldtexture.jpg);border: ridge 4px gold;border-radius: 10px;'}, 'static_icons': [], 'icons': [], 'css': {}, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'time_format': '24hr', 'entity': 'clock.clock', 'title_is_friendly_name': 1})
    
        widgets["default-device-tracker-lindasiphone"] = new baseswitch("default-device-tracker-lindasiphone", "", "simplyred", {'widget_type': 'baseswitch', 'entity': 'device_tracker.lindasiphone', 'state_active': 'home', 'state_inactive': 'not_home', 'enable': 0, 'state_text': 1, 'post_service_active': {'service': 'device_tracker/see', 'dev_id': '', 'location_name': 'home'}, 'post_service_inactive': {'service': 'device_tracker/see', 'dev_id': '', 'location_name': 'not_home'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': ''}, 'icons': {'icon_on': 'fa-user', 'icon_off': 'fa-user'}, 'static_icons': [], 'css': {'icon_style_active': 'color: gold;', 'icon_style_inactive': 'color: #888;'}, 'static_css': {'title_style': 'color: gold;font-weight: 900;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: white;font-weight: bold;', 'widget_style': ''}, 'state_map': {'home': 'HOME', 'not_home': 'AWAY'}, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'time_format': '24hr', 'title_is_friendly_name': 1})
    
        widgets["default-device-tracker-matrix"] = new baseswitch("default-device-tracker-matrix", "", "simplyred", {'widget_type': 'baseswitch', 'entity': 'device_tracker.matrix', 'state_active': 'home', 'state_inactive': 'not_home', 'enable': 0, 'state_text': 1, 'post_service_active': {'service': 'device_tracker/see', 'dev_id': '', 'location_name': 'home'}, 'post_service_inactive': {'service': 'device_tracker/see', 'dev_id': '', 'location_name': 'not_home'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': ''}, 'icons': {'icon_on': 'fa-user', 'icon_off': 'fa-user'}, 'static_icons': [], 'css': {'icon_style_active': 'color: gold;', 'icon_style_inactive': 'color: #888;'}, 'static_css': {'title_style': 'color: gold;font-weight: 900;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: white;font-weight: bold;', 'widget_style': ''}, 'state_map': {'home': 'HOME', 'not_home': 'AWAY'}, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'time_format': '24hr', 'title_is_friendly_name': 1})
    
        widgets["default-device-tracker-disasiphone"] = new baseswitch("default-device-tracker-disasiphone", "", "simplyred", {'widget_type': 'baseswitch', 'entity': 'device_tracker.disasiphone', 'state_active': 'home', 'state_inactive': 'not_home', 'enable': 0, 'state_text': 1, 'post_service_active': {'service': 'device_tracker/see', 'dev_id': '', 'location_name': 'home'}, 'post_service_inactive': {'service': 'device_tracker/see', 'dev_id': '', 'location_name': 'not_home'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': ''}, 'icons': {'icon_on': 'fa-user', 'icon_off': 'fa-user'}, 'static_icons': [], 'css': {'icon_style_active': 'color: gold;', 'icon_style_inactive': 'color: #888;'}, 'static_css': {'title_style': 'color: gold;font-weight: 900;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: white;font-weight: bold;', 'widget_style': ''}, 'state_map': {'home': 'HOME', 'not_home': 'AWAY'}, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'time_format': '24hr', 'title_is_friendly_name': 1})
    
        widgets["default-device-tracker-quack"] = new baseswitch("default-device-tracker-quack", "", "simplyred", {'widget_type': 'baseswitch', 'entity': 'device_tracker.quack', 'state_active': 'home', 'state_inactive': 'not_home', 'enable': 0, 'state_text': 1, 'post_service_active': {'service': 'device_tracker/see', 'dev_id': '', 'location_name': 'home'}, 'post_service_inactive': {'service': 'device_tracker/see', 'dev_id': '', 'location_name': 'not_home'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': ''}, 'icons': {'icon_on': 'fa-user', 'icon_off': 'fa-user'}, 'static_icons': [], 'css': {'icon_style_active': 'color: gold;', 'icon_style_inactive': 'color: #888;'}, 'static_css': {'title_style': 'color: gold;font-weight: 900;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: white;font-weight: bold;', 'widget_style': ''}, 'state_map': {'home': 'HOME', 'not_home': 'AWAY'}, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'time_format': '24hr', 'title_is_friendly_name': 1})
    
        widgets["default-group-vardagsrum"] = new baselight("default-group-vardagsrum", "", "simplyred", {'widget_type': 'baselight', 'entity': 'group.vardagsrum', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'group.vardagsrum'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'group.vardagsrum'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-circle', 'icon_off': 'fa-circle-thin'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: gold;font-weight: 900;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': ''}, 'css': {'icon_style_active': 'color: gold;', 'icon_style_inactive': 'color: #888;'}, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'time_format': '24hr', 'title_is_friendly_name': 1})
    
        widgets["default-light-hall"] = new baselight("default-light-hall", "", "simplyred", {'widget_type': 'baselight', 'entity': 'light.hall', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.hall'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.hall'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-circle', 'icon_off': 'fa-circle-thin'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: gold;font-weight: 900;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': ''}, 'css': {'icon_style_active': 'color: gold;', 'icon_style_inactive': 'color: #888;'}, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'time_format': '24hr', 'title_is_friendly_name': 1})
    
        widgets["default-light-soffa"] = new baselight("default-light-soffa", "", "simplyred", {'widget_type': 'baselight', 'entity': 'light.soffa', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.soffa'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.soffa'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-circle', 'icon_off': 'fa-circle-thin'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: gold;font-weight: 900;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': ''}, 'css': {'icon_style_active': 'color: gold;', 'icon_style_inactive': 'color: #888;'}, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'time_format': '24hr', 'title_is_friendly_name': 1})
    
        widgets["default-light-matbord"] = new baselight("default-light-matbord", "", "simplyred", {'widget_type': 'baselight', 'entity': 'light.matbord', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.matbord'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.matbord'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-circle', 'icon_off': 'fa-circle-thin'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: gold;font-weight: 900;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': ''}, 'css': {'icon_style_active': 'color: gold;', 'icon_style_inactive': 'color: #888;'}, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'time_format': '24hr', 'title_is_friendly_name': 1})
    
        widgets["default-group-kok"] = new baselight("default-group-kok", "", "simplyred", {'widget_type': 'baselight', 'entity': 'group.kok', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'group.kok'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'group.kok'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-circle', 'icon_off': 'fa-circle-thin'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: gold;font-weight: 900;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': ''}, 'css': {'icon_style_active': 'color: gold;', 'icon_style_inactive': 'color: #888;'}, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'time_format': '24hr', 'title_is_friendly_name': 1})
    
        widgets["default-light-skarbrada"] = new baselight("default-light-skarbrada", "", "simplyred", {'widget_type': 'baselight', 'entity': 'light.skarbrada', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.skarbrada'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.skarbrada'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-circle', 'icon_off': 'fa-circle-thin'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: gold;font-weight: 900;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': ''}, 'css': {'icon_style_active': 'color: gold;', 'icon_style_inactive': 'color: #888;'}, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'time_format': '24hr', 'title_is_friendly_name': 1})
    
        widgets["default-light-klocka"] = new baselight("default-light-klocka", "", "simplyred", {'widget_type': 'baselight', 'entity': 'light.klocka', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.klocka'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.klocka'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-circle', 'icon_off': 'fa-circle-thin'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: gold;font-weight: 900;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': ''}, 'css': {'icon_style_active': 'color: gold;', 'icon_style_inactive': 'color: #888;'}, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'time_format': '24hr', 'title_is_friendly_name': 1})
    
        widgets["default-light-hyllor"] = new baselight("default-light-hyllor", "", "simplyred", {'widget_type': 'baselight', 'entity': 'light.hyllor', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.hyllor'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.hyllor'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-circle', 'icon_off': 'fa-circle-thin'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: gold;font-weight: 900;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': ''}, 'css': {'icon_style_active': 'color: gold;', 'icon_style_inactive': 'color: #888;'}, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'time_format': '24hr', 'title_is_friendly_name': 1})
    
        widgets["default-light-koksbord"] = new baselight("default-light-koksbord", "", "simplyred", {'widget_type': 'baselight', 'entity': 'light.koksbord', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.koksbord'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.koksbord'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-circle', 'icon_off': 'fa-circle-thin'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: gold;font-weight: 900;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': ''}, 'css': {'icon_style_active': 'color: gold;', 'icon_style_inactive': 'color: #888;'}, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'time_format': '24hr', 'title_is_friendly_name': 1})
    
        widgets["default-scene-skymning"] = new baseswitch("default-scene-skymning", "", "simplyred", {'widget_type': 'baseswitch', 'entity': 'scene.skymning', 'state_inactive': 'scening', 'state_active': 'stillscening', 'enable': 1, 'momentary': 1000, 'ignore_state': 1, 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'scene.skymning'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'scene.skymning'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': ''}, 'icons': {'icon_on': 'fa-square', 'icon_off': 'fa-square'}, 'static_icons': [], 'css': {'icon_style_active': 'color: gold;', 'icon_style_inactive': 'color: #888;'}, 'static_css': {'title_style': 'color: gold;font-weight: 900;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: white;font-weight: bold;', 'widget_style': ''}, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'time_format': '24hr', 'title_is_friendly_name': 1})
    
        widgets["default-scene-mysljus"] = new baseswitch("default-scene-mysljus", "", "simplyred", {'widget_type': 'baseswitch', 'entity': 'scene.mysljus', 'state_inactive': 'scening', 'state_active': 'stillscening', 'enable': 1, 'momentary': 1000, 'ignore_state': 1, 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'scene.mysljus'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'scene.mysljus'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': ''}, 'icons': {'icon_on': 'fa-square', 'icon_off': 'fa-square'}, 'static_icons': [], 'css': {'icon_style_active': 'color: gold;', 'icon_style_inactive': 'color: #888;'}, 'static_css': {'title_style': 'color: gold;font-weight: 900;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: white;font-weight: bold;', 'widget_style': ''}, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'time_format': '24hr', 'title_is_friendly_name': 1})
    
        widgets["default-switch-flux"] = new baseswitch("default-switch-flux", "", "simplyred", {'widget_type': 'baseswitch', 'entity': 'switch.flux', 'state_active': 'on', 'state_inactive': 'off', 'enable': 1, 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'switch.flux'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'switch.flux'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': ''}, 'icons': {'icon_on': 'fa-circle', 'icon_off': 'fa-circle-thin'}, 'static_icons': [], 'css': {'icon_style_active': 'color: gold;', 'icon_style_inactive': 'color: #888;'}, 'static_css': {'title_style': 'color: gold;font-weight: 900;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: white;font-weight: bold;', 'widget_style': ''}, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'time_format': '24hr', 'title_is_friendly_name': 1})
    

    // Setup click handler to cancel timeout navigations

    $( ".gridster" ).click(function(){
        clearTimeout(myTimeout);
    });

    // Set up timeout

    var myTimeout

    if (location.search != "")
    {
        var query = location.search.substr(1);
        var result = {};
        query.split("&").forEach(function(part) {
        var item = part.split("=");
        result[item[0]] = decodeURIComponent(item[1]);
        });

        if ("timeout" in result && "return" in result)
        {
            url = result.return
            argcount = 0
            for (arg in result)
            {
                if (arg != "timeout" && arg != "return")
                {
                    if (argcount == 0)
                    {
                        url += "?";
                    }
                    else
                    {
                        url += "?";
                    }
                    argcount ++;
                    url += arg + "=" + result[arg]
                }
            }
            myTimeout = setTimeout(function() { navigate(url); }, result.timeout * 1000);
        }
    }

    // Start listening for HA Events
    if (location.protocol == 'https:')
    {
        wsprot = "wss:"
    }
    else
    {
        wsprot = "ws:"
    }
    var stream_url = wsprot + '//' + location.host + '/stream'
    ha_status(stream_url, "Main Panel", widgets);

});