alias: "Tid: 23:00 -> Släck alla lampor på bottenvåning om ingen hemma"
trigger:
  platform: time
  at: '23:00:00'
condition:
  condition: state
  entity_id: group.familj
  state: not_home
action:
  - service: light.turn_off
    entity_id: group.all_lights
