alias: "Tid: 10:30 -> Släck alla lampor på bottenvåning om ingen hemma"
trigger:
  platform: time
  at: '10:30:00'
condition:
  condition: state
  entity_id: group.familj
  state: not_home
action:
  - service: light.turn_off
    entity_id: group.bottenvaning
